// src/types/journal.ts

// ---------- Core enums ----------
export type Mood =
  | "✨ uplifted"
  | "🙂 okay"
  | "😐 neutral"
  | "😕 low"
  | "😞 heavy";

export type Chakra =
  | "Root"
  | "Sacral"
  | "Solar Plexus"
  | "Heart"
  | "Throat"
  | "Third Eye"
  | "Crown";

export type Emotion =
  | "calm"
  | "anxious"
  | "angry"
  | "sad"
  | "grateful"
  | "tired"
  | "excited"
  | "grounded";

export type BodyArea =
  | "head"
  | "throat"
  | "chest"
  | "solar_plexus"
  | "belly"
  | "hips"
  | "legs"
  | "feet";

export type Visibility = "private" | "community";

export type EntryKind =
  | "journal"            // regular entry
  | "dream"              // dream journal mode
  | "checkin"            // created from quick check-in/voice
  | "event_reflection"   // after class/event
  | "meal_note";         // food as medicine note

// ---------- Guided prompts ----------
export type PromptCategory = "daily" | "body" | "emotion" | "dream";
export type GuidedPrompt = {
  id: string;
  text: string;
  category: PromptCategory;
};

// ---------- Media ----------
export type JournalMedia = {
  id: string;
  kind: "image" | "audio" | "video";
  /** If you store files remotely, prefer storageUrl and keep dataUrl optional for local previews */
  dataUrl?: string;
  storageUrl?: string;
  caption?: string;
};

// ---------- Tarot & Crystals ----------
export type TarotAttachment = {
  deck?: string;                // e.g. "Thoth", "RWS"
  cards: string[];              // e.g. ["The Moon", "6 of Cups"]
  spreadName?: string;          // optional spread label
};

export type CrystalAttachment = {
  crystals: string[];           // e.g. ["Black Tourmaline", "Amethyst"]
  intention?: string;           // short note about why
};

// ---------- AI / Insights ----------
export type AISuggestions = {
  mantras?: string[];
  breaths?: string[];
  poses?: string[];
  snacks?: string[];            // Food as Medicine
  crystals?: string[];
  affirmations?: string[];
};

export type AIFields = {
  mentorSummary?: string;       // “Summarize my last 5 entries” result per entry
  meditationScript?: string;    // personalized meditation generated by Mentor
  suggestions?: AISuggestions;  // structured recommendations
};

// ---------- Links to other features ----------
export type EntryLinks = {
  eventId?: string;     // Events & Classes
  checkInId?: string;   // Check-In
  mealId?: string;      // Food as Medicine
  insightsId?: string;  // any Insights document/record id
};

// ---------- The Journal Entry ----------
export type JournalEntry = {
  id: string;

  // bookkeeping (frontend-first; easy to map to Supabase later)
  userId?: string;          // optional for local-only; include when syncing
  createdAt: number;        // ms epoch
  updatedAt?: number;       // ms epoch
  deletedAt?: number | null;

  // entry content
  kind: EntryKind;          // "journal" | "dream" | ...
  title?: string;           // optional short title
  text: string;

  // guided prompt used for this entry (either reference or inline text)
  prompt?: {
    id?: string;
    text?: string;
    category?: PromptCategory;
  };

  // mood tracking
  moodBefore?: Mood;
  moodAfter?: Mood;

  // tagging system
  tags?: {
    chakras?: Chakra[];
    emotions?: Emotion[];
    body?: BodyArea[];
    keywords?: string[];     // freeform keywords for search/trends
  };

  // attachments
  media?: JournalMedia[];
  tarot?: TarotAttachment;
  crystals?: CrystalAttachment;

  // sharing & privacy
  visibility?: Visibility;         // "private" (default) or "community"
  sharedToCommunity?: boolean;     // kept for backwards-compat; prefer visibility

  // automations / provenance
  voiceToText?: boolean;           // created from voice
  source?: "manual" | "voice" | "import" | "auto";

  // lock / ritual
  locked?: boolean;                // Sacred Space lock
  lockAnimation?: "ankh" | "smoke" | "none";

  // cross-feature links
  links?: EntryLinks;

  // AI / Mentor
  ai?: AIFields;

  // lightweight analytics (optional but useful)
  wordCount?: number;
  sentiment?: number;              // -1..1 for future analysis
};

// ---------- Convenience: default prompts you can render in the UI ----------
export const DEFAULT_GUIDED_PROMPTS: GuidedPrompt[] = [
  { id: "p1", text: "What energy are you carrying today?", category: "daily" },
  { id: "p2", text: "Where did you feel resistance in your body?", category: "body" },
  { id: "p3", text: "What emotion is most present right now?", category: "emotion" },
  { id: "p4", text: "What symbols or scenes appeared in your dream?", category: "dream" },
];

// ---------- Factory helper so new entries are consistent ----------
// NOTE: no Date.now() or UUID here — we’ll fill those after mount
export function createEmptyJournalEntry(partial: Partial<JournalEntry> = {}): JournalEntry {
  return {
    id: "",
    createdAt: 0,
    updatedAt: 0,
    kind: partial.kind ?? "journal",
    text: "",
    visibility: "private",
    locked: false,
    ...partial,
  };
}
